/// Reviewed administration surface, not permission inferred from a method name.
///
/// The gateway must resolve a definition from this compiled catalog, require
/// advertised public method metadata, validate its schema and apply its risk.
/// An entry with [AdminOperationDefinition.blockedReason] is discoverable but
/// cannot be executed through the schema-driven administration surface.
enum AdminDomain {
  dashboard,
  storage,
  datasets,
  shares,
  dataProtection,
  network,
  credentials,
  apps,
  containers,
  virtualization,
  reporting,
  system,
  alerts,
  jobs,
  enterprise,
}

extension AdminDomainPresentation on AdminDomain {
  String get label => switch (this) {
    AdminDomain.dashboard => 'Overview',
    AdminDomain.storage => 'Storage',
    AdminDomain.datasets => 'Datasets & snapshots',
    AdminDomain.shares => 'Shares',
    AdminDomain.dataProtection => 'Data protection',
    AdminDomain.network => 'Network',
    AdminDomain.credentials => 'Users & credentials',
    AdminDomain.apps => 'Applications',
    AdminDomain.containers => 'Containers',
    AdminDomain.virtualization => 'Virtual machines',
    AdminDomain.reporting => 'Reporting',
    AdminDomain.system => 'System settings',
    AdminDomain.alerts => 'Alerts',
    AdminDomain.jobs => 'Jobs',
    AdminDomain.enterprise => 'Enterprise',
  };
}

enum AdminRisk { read, change, destructive, disruptive }

final class AdminOperationDefinition {
  const AdminOperationDefinition({
    required this.id,
    required this.domain,
    required this.title,
    required this.method,
    required this.risk,
    required this.description,
    this.warning,
    this.blockedReason,
  });

  const AdminOperationDefinition.read(
    this.domain,
    this.method,
    this.title,
    this.description, {
    this.blockedReason,
  }) : id = method,
       risk = AdminRisk.read,
       warning = null;

  const AdminOperationDefinition.change(
    this.domain,
    this.method,
    this.title,
    this.description, {
    required this.warning,
    this.blockedReason,
  }) : id = method,
       risk = AdminRisk.change;

  const AdminOperationDefinition.destructive(
    this.domain,
    this.method,
    this.title,
    this.description, {
    required this.warning,
    this.blockedReason,
  }) : id = method,
       risk = AdminRisk.destructive;

  const AdminOperationDefinition.disruptive(
    this.domain,
    this.method,
    this.title,
    this.description, {
    required this.warning,
    this.blockedReason,
  }) : id = method,
       risk = AdminRisk.disruptive;

  final String id;
  final AdminDomain domain;
  final String title;
  final String method;
  final AdminRisk risk;
  final String description;
  final String? warning;
  final String? blockedReason;

  bool get requiresConfirmation => risk != AdminRisk.read;
  bool get requiresTypedConfirmation =>
      risk == AdminRisk.destructive || risk == AdminRisk.disruptive;
}

const _storageWizard =
    'A topology-aware storage wizard with dependency checks is required.';
const _diskNative =
    'Use the native disk inventory and settings review with passive identity, boot ownership and redacted field checks.';
const _poolMaintenanceNative =
    'Use the native pool maintenance workspace for pool identity, schedule impact and owned scrub-job verification.';
const _encryptionFlow =
    'A dedicated encryption and recovery-material workflow is required.';
const _networkTransaction =
    'A reconnect-safe test, check-in and timed rollback workflow is required.';
const _secretFlow =
    'A dedicated secret-entry, redaction and one-time disclosure workflow is required.';
const _fileFlow =
    'A secure upload or download workflow is required; JSON forms cannot transfer this file.';
const _terminalFlow =
    'An authenticated streaming terminal with session expiry and resize handling is required.';
const _appSchemaFlow =
    'A catalog-driven installer with dynamic values, storage and network validation is required.';
const _permissionFlow =
    'A permissions editor with identity resolution and recursive-impact preview is required.';
const _haFlow =
    'A node-aware HA workflow with active/standby and failover checks is required.';
const _accountFlow =
    'A dedicated account workflow with built-in and last-administrator protection is required.';
const _shareWarning =
    'This changes network access to stored data. Review paths, client access and active sessions.';
const _shareDeleteWarning =
    'This removes the selected share configuration and can disconnect clients. Review dependent mappings first.';
const _nativeShareFlow =
    'Use the native SMB/NFS workspace for exact filesystem identity, access restrictions and client-impact review.';
const _taskWarning =
    'This changes an automated task. Review source, destination, schedule and retention before saving.';
const _taskDeleteWarning =
    'This removes the selected task. Future scheduled protection will stop.';
const _transferWarning =
    'This may overwrite or remove destination data according to the saved task. Review direction and retention first.';
const _rsyncNative =
    'Use the native Rsync workspace for SSH trust, exact source identity, overwrite review and explicit job checks. Generic forms must not trigger remote validation or key scans.';
const _systemPowerNative =
    'Use the native system power workspace for exact server identity, standalone readiness and interruption review. A disconnect is not proof of reboot or shutdown completion.';
const _serviceWarning =
    'This changes service behavior and may interrupt connected clients.';
const _vmWarning =
    'This changes guest availability. Save guest work and verify the exact virtual machine.';

/// Public 25.10 method names checked against api.truenas.com on 2026-09-12.
/// Runtime method/version/schema/role checks are additional mandatory gates.
/// Blocked entries can also document a missing version-specific public adapter.
const List<AdminOperationDefinition> adminOperationDefinitions = [
  AdminOperationDefinition.read(
    AdminDomain.dashboard,
    'system.info',
    'System information',
    'Identity, release, uptime and hardware reported by this server.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.dashboard,
    'webui.main.dashboard.sys_info',
    'Dashboard hardware summary',
    'Server-provided dashboard hardware facts.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.storage,
    'pool.query',
    'Storage pools',
    'Pool status, topology and capacity inventory.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.storage,
    'disk.query',
    'Physical disks',
    'Disk identifiers, device details and configuration.',
    blockedReason: _diskNative,
  ),
  AdminOperationDefinition.read(
    AdminDomain.storage,
    'disk.temperatures',
    'Drive temperatures',
    'Available sensor readings; unsupported sensors remain unavailable.',
    blockedReason: 'Temperature collection can wake disks and requires a separate power-aware request review.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'disk.update',
    'Edit disk settings',
    'Configure standby, power and supported disk options.',
    warning: 'Power and standby settings affect disk responsiveness. Verify the disk identifier.',
    blockedReason: _diskNative,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.storage,
    'disk.wipe',
    'Wipe disk',
    'Erase data from a physical device.',
    warning: 'Disk contents are permanently destroyed.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.create',
    'Create pool',
    'Choose disk topology for a new pool.',
    warning: 'Selected devices may be erased.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.read(
    AdminDomain.storage,
    'pool.import_find',
    'Find importable pools',
    'Scan devices for pools available to import.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.import_pool',
    'Import pool',
    'Bring an existing pool into this server.',
    warning: 'Import can mount datasets and affect sharing.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.storage,
    'pool.export',
    'Export or destroy pool',
    'Disconnect or permanently destroy a pool.',
    warning:
        'Pool data and dependent services may become unavailable or be erased.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.attach',
    'Attach pool device',
    'Attach a device to an existing pool topology.',
    warning: 'This modifies storage redundancy.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.storage,
    'pool.detach',
    'Detach pool device',
    'Remove a device from a mirrored VDEV.',
    warning: 'This can reduce redundancy.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.storage,
    'pool.offline',
    'Offline pool device',
    'Take a selected pool device offline.',
    warning: 'Taking the wrong device offline can make data unavailable.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.online',
    'Online pool device',
    'Return a pool device to service.',
    warning: 'A resilver may start.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.storage,
    'pool.remove',
    'Remove VDEV',
    'Remove a supported device or VDEV.',
    warning: 'Storage topology and redundancy will change.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.replace',
    'Replace disk',
    'Replace a failed or selected pool device.',
    warning: 'The replacement device may be erased.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.expand',
    'Expand pool',
    'Expand storage using available device capacity.',
    warning: 'Pool layout changes may be irreversible.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.update',
    'Edit pool topology',
    'Update a pool and add supported VDEVs.',
    warning: 'Adding VDEVs changes data placement and redundancy.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.storage,
    'pool.upgrade',
    'Upgrade pool features',
    'Enable newer ZFS pool features.',
    warning: 'Older TrueNAS or ZFS versions may no longer import this pool.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.read(
    AdminDomain.storage,
    'pool.scrub.query',
    'Scrub schedules',
    'Configured storage integrity check schedules.',
    blockedReason: _poolMaintenanceNative,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.scrub.create',
    'Schedule scrub',
    'Create a pool integrity check schedule.',
    warning: 'Scrubs increase disk load during the selected schedule.',
    blockedReason: _poolMaintenanceNative,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.scrub.update',
    'Edit scrub schedule',
    'Update an existing integrity check schedule.',
    warning: 'Review frequency and disk load.',
    blockedReason: _poolMaintenanceNative,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.storage,
    'pool.scrub.delete',
    'Delete scrub schedule',
    'Remove a scheduled integrity check.',
    warning: 'Automatic scrubs for this schedule will stop.',
    blockedReason: _poolMaintenanceNative,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.scrub.run',
    'Run scheduled scrub',
    'Run a configured scrub task.',
    warning: 'This increases disk load and can reduce throughput.',
    blockedReason: _poolMaintenanceNative,
  ),
  AdminOperationDefinition.change(
    AdminDomain.storage,
    'pool.scrub.scrub',
    'Control pool scrub',
    'Start, stop or pause a scrub for a selected pool.',
    warning: 'Stopping a scrub leaves its integrity check unfinished.',
    blockedReason: _poolMaintenanceNative,
  ),
  AdminOperationDefinition.read(
    AdminDomain.datasets,
    'pool.dataset.query',
    'Dataset tree',
    'Datasets, Zvols and reported properties.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.dataset.create',
    'Create dataset or Zvol',
    'Create storage beneath an existing pool.',
    warning: 'Storage properties affect application compatibility.',
    blockedReason: 'Use Quick management for safe child filesystem creation. Zvols and advanced properties need a storage wizard.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.dataset.update',
    'Edit dataset properties',
    'Update compression, quotas and other dataset properties.',
    warning: 'Dataset properties can change capacity limits and application compatibility.',
    blockedReason: 'Use the dedicated Dataset properties editor for reviewed filesystem quotas, reservations and inherited settings. Other properties need specialized storage workflows.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.dataset.rename',
    'Rename dataset',
    'Change a dataset path.',
    warning: 'Shares, applications and tasks can reference the old path.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.datasets,
    'pool.dataset.delete',
    'Delete dataset',
    'Permanently remove a dataset and its contents.',
    warning: 'There is no undo for dataset deletion.',
    blockedReason: 'Use Quick management for exact-target non-recursive deletion with dependency checks.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.datasets,
    'pool.dataset.get_quota',
    'User and group quotas',
    'Inspect quota usage and limits for a dataset.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.dataset.set_quota',
    'Set user or group quotas',
    'Change per-identity storage or object limits.',
    warning: 'Reduced quotas can prevent users and applications from writing.',
    blockedReason: 'Use the native quota editor for resolved identities, exact byte/object limits and reviewed storage impact.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.datasets,
    'pool.snapshot.query',
    'Snapshots',
    'Point-in-time snapshots and their properties.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.snapshot.create',
    'Create snapshot',
    'Capture a dataset at a point in time.',
    warning: 'Snapshots retain data and consume pool capacity.',
    blockedReason:
        'Use Quick management for validated single-dataset snapshot creation.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.snapshot.clone',
    'Clone snapshot',
    'Create a writable dataset from a snapshot.',
    warning: 'The clone depends on its source snapshot.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.datasets,
    'pool.snapshot.delete',
    'Delete snapshot',
    'Remove a recovery point.',
    warning: 'This recovery point cannot be restored after deletion.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.datasets,
    'pool.snapshot.rollback',
    'Roll back dataset',
    'Revert stored data to a snapshot.',
    warning: 'Data written after the snapshot can be permanently lost.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.snapshot.hold',
    'Hold snapshot',
    'Prevent normal deletion of a selected snapshot.',
    warning: 'Held snapshots can prevent cleanup and retain storage usage.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.snapshot.release',
    'Release snapshot hold',
    'Allow normal snapshot deletion again.',
    warning: 'A retention policy can subsequently remove this recovery point.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.datasets,
    'filesystem.getacl',
    'Inspect permissions',
    'Read dataset ownership and access control entries.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'filesystem.setacl',
    'Edit access control',
    'Apply NFSv4 or POSIX access control entries.',
    warning: 'Incorrect permissions can expose data or lock users out.',
    blockedReason: _permissionFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'filesystem.setperm',
    'Edit basic permissions',
    'Change owner, group and permission bits.',
    warning: 'Recursive changes affect files throughout the selected tree.',
    blockedReason: _permissionFlow,
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.datasets,
    'pool.dataset.lock',
    'Lock encrypted dataset',
    'Unmount and lock encrypted storage.',
    warning: 'Shares and applications using this dataset can stop.',
    blockedReason: _encryptionFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.dataset.unlock',
    'Unlock encrypted dataset',
    'Supply key material to unlock encrypted storage.',
    warning: 'Unlocking exposes dataset contents to configured consumers.',
    blockedReason: _encryptionFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.datasets,
    'pool.dataset.change_key',
    'Change encryption key',
    'Rotate a dataset key or passphrase.',
    warning:
        'Losing the current recovery material can permanently lose access.',
    blockedReason: _encryptionFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.datasets,
    'pool.dataset.export_key',
    'Export dataset key',
    'Retrieve recovery material for one dataset.',
    blockedReason: _encryptionFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.datasets,
    'pool.dataset.export_keys',
    'Export recovery keys',
    'Retrieve encrypted storage recovery material.',
    blockedReason: _encryptionFlow,
  ),

  AdminOperationDefinition.read(
    AdminDomain.shares,
    'sharing.smb.query',
    'SMB shares',
    'Windows and macOS file-share inventory.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'sharing.smb.create',
    'Create SMB share',
    'Expose a dataset path using SMB.',
    warning: _shareWarning,
    blockedReason: _nativeShareFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'sharing.smb.update',
    'Edit SMB share',
    'Update share access and supported options.',
    warning: _shareWarning,
    blockedReason: _nativeShareFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'sharing.smb.delete',
    'Delete SMB share',
    'Remove the selected SMB export.',
    warning: _shareDeleteWarning,
    blockedReason: _nativeShareFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'sharing.smb.presets',
    'SMB presets',
    'Server-supported SMB use-case presets.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'smb.config',
    'SMB service configuration',
    'Global SMB settings.',
    blockedReason: 'Use the native SMB settings workspace for protected configuration projection and verified dependencies.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'smb.update',
    'Configure SMB service',
    'Update global SMB behavior.',
    warning: _serviceWarning,
    blockedReason: 'Use native SMB configuration review for identity, directory-service, protocol security and restart safeguards.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'sharing.nfs.query',
    'NFS shares',
    'Unix and Linux file-share inventory.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'sharing.nfs.create',
    'Create NFS share',
    'Export a path to permitted NFS clients.',
    warning: _shareWarning,
    blockedReason: _nativeShareFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'sharing.nfs.update',
    'Edit NFS share',
    'Update export access, networks and identity mapping.',
    warning: _shareWarning,
    blockedReason: _nativeShareFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'sharing.nfs.delete',
    'Delete NFS share',
    'Remove the selected NFS export.',
    warning: _shareDeleteWarning,
    blockedReason: _nativeShareFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nfs.config',
    'NFS service configuration',
    'Global NFS settings.',
    blockedReason: 'Use the native NFS settings workspace for protected configuration projection and export dependencies.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nfs.update',
    'Configure NFS service',
    'Update global NFS behavior.',
    warning: _serviceWarning,
    blockedReason: 'Use native stopped-service NFS review for protocol, export, security and restart safeguards.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nfs.get_nfs3_clients',
    'NFSv3 clients',
    'Reported NFSv3 client activity.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nfs.get_nfs4_clients',
    'NFSv4 clients',
    'Reported NFSv4 client activity.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.global.config',
    'iSCSI configuration',
    'Global block-sharing settings.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.global.update',
    'Configure iSCSI',
    'Update global target service settings.',
    warning: _serviceWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.global.sessions',
    'iSCSI sessions',
    'Connected block-storage initiators.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.portal.query',
    'iSCSI portals',
    'Configured target listening endpoints.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.portal.listen_ip_choices',
    'iSCSI listener address choices',
    'Server-offered static addresses for portal listening.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.portal.create',
    'Create iSCSI portal',
    'Add a block-sharing listening endpoint.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.portal.update',
    'Edit iSCSI portal',
    'Change listening addresses or portal options.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'iscsi.portal.delete',
    'Delete iSCSI portal',
    'Remove an iSCSI endpoint.',
    warning: _shareDeleteWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.initiator.query',
    'iSCSI initiators',
    'Configured initiator access groups.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.initiator.create',
    'Create initiator group',
    'Define allowed block-storage clients.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.initiator.update',
    'Edit initiator group',
    'Change permitted initiators.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'iscsi.initiator.delete',
    'Delete initiator group',
    'Remove an initiator access group.',
    warning: _shareDeleteWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.target.query',
    'iSCSI targets',
    'Target names and access mappings.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.target.get_instance',
    'iSCSI target details',
    'Read an exact target before a reviewed change.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.target.validate_name',
    'Validate iSCSI target name',
    'Check a proposed new target name without creating it.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.target.create',
    'Create iSCSI target',
    'Define a target and permitted portal groups.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.target.update',
    'Edit iSCSI target',
    'Change target options and access mappings.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'iscsi.target.delete',
    'Delete iSCSI target',
    'Remove a block-storage target.',
    warning: _shareDeleteWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.extent.query',
    'iSCSI extents',
    'Backing devices and files exposed to targets.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.extent.get_instance',
    'iSCSI extent detail',
    'Exact extent configuration for reviewed edits.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.extent.create',
    'Create iSCSI extent',
    'Select a backing file or device.',
    warning: 'Exposing a device used elsewhere can corrupt data.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.extent.update',
    'Edit iSCSI extent',
    'Change backing storage options.',
    warning: 'Changing a live backing device can corrupt client data.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'iscsi.extent.delete',
    'Delete iSCSI extent',
    'Remove a backing storage export.',
    warning: 'Backing files may be deleted depending on options.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.targetextent.query',
    'Target extent mappings',
    'Associations between targets, extents and LUNs.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.targetextent.create',
    'Map target extent',
    'Expose an extent through a selected target.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.targetextent.update',
    'Edit target extent mapping',
    'Update a target, extent or LUN mapping.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'iscsi.targetextent.delete',
    'Remove target extent mapping',
    'Detach an extent from a target.',
    warning: _shareDeleteWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'iscsi.auth.query',
    'iSCSI authentication',
    'Configured CHAP authentication records.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'iscsi.auth.create',
    'Create CHAP authentication',
    'Add credentials for block-storage clients.',
    warning: 'Credentials grant access to block data.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nvmet.global.config',
    'NVMe-oF configuration',
    'Global NVMe target settings.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nvmet.subsys.query',
    'NVMe subsystems',
    'Configured NVMe-over-Fabrics subsystems.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nvmet.subsys.create',
    'Create NVMe subsystem',
    'Define an NVMe target subsystem.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nvmet.subsys.update',
    'Edit NVMe subsystem',
    'Update subsystem identity and access options.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'nvmet.subsys.delete',
    'Delete NVMe subsystem',
    'Remove an NVMe target subsystem.',
    warning: _shareDeleteWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nvmet.port.query',
    'NVMe ports',
    'NVMe target transport endpoints.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nvmet.port.transport_address_choices',
    'NVMe transport address choices',
    'Server-advertised transport binding addresses and descriptions.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nvmet.port.create',
    'Create NVMe port',
    'Add an NVMe transport endpoint.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nvmet.port.update',
    'Edit NVMe port',
    'Change NVMe transport configuration.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'nvmet.port.delete',
    'Delete NVMe port',
    'Remove an NVMe endpoint.',
    warning: _shareDeleteWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nvmet.namespace.query',
    'NVMe namespaces',
    'Backing storage exposed by NVMe targets.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'nvmet.namespace.delete',
    'Remove NVMe namespace configuration',
    'Remove namespace configuration through the native backing-preserving review.',
    warning: 'Namespace configuration must be recreated to restore this mapping. Backing-file removal is unavailable in the native workflow.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nvmet.namespace.create',
    'Create NVMe namespace',
    'Associate a backing device with a subsystem.',
    warning: 'Exposing a device used elsewhere can corrupt data.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nvmet.host.query',
    'NVMe hosts',
    'Permitted NVMe initiators; credentials require a protected viewer.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nvmet.host.create',
    'Register unassociated NVMe host',
    'Register an initiator NQN without authentication or subsystem mappings.',
    warning: 'DH-CHAP authentication is not configured. This is not proof of initiator identity or access.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nvmet.host.update',
    'Change unassociated NVMe host NQN',
    'NQN-only editing through the protected uncredentialed-host workflow.',
    warning: 'Existing initiator configuration may need to change. NVMe configuration reloads; concurrent administration is not excluded.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'nvmet.host.delete',
    'Delete NVMe host',
    'Remove an unassociated NVMe initiator identity.',
    warning: _shareDeleteWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nvmet.host_subsys.query',
    'NVMe host mappings',
    'Host access associations for subsystems.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nvmet.host_subsys.create',
    'Permit NVMe host',
    'Associate a host with an NVMe subsystem.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'nvmet.host_subsys.delete',
    'Remove NVMe host access',
    'Remove host access to a subsystem.',
    warning: _shareDeleteWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'nvmet.port_subsys.query',
    'NVMe port mappings',
    'Associations between endpoints and subsystems.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.shares,
    'nvmet.port_subsys.create',
    'Map NVMe port',
    'Expose a subsystem on an endpoint.',
    warning: _shareWarning,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.shares,
    'nvmet.port_subsys.delete',
    'Remove NVMe port mapping',
    'Stop exposing a subsystem on an endpoint.',
    warning: _shareDeleteWarning,
  ),
  AdminOperationDefinition.read(
    AdminDomain.shares,
    'sharing.webshare.query',
    'WebShare',
    'Version-dependent browser file sharing.',
    blockedReason: 'A reviewed public WebShare method adapter is not available for the 25.10 baseline.',
  ),

  AdminOperationDefinition.read(
    AdminDomain.dataProtection,
    'pool.snapshottask.query',
    'Periodic snapshot tasks',
    'Schedules and retention for automatic snapshots.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.dataProtection,
    'pool.snapshottask.create',
    'Schedule snapshots',
    'Create a periodic snapshot policy.',
    warning: _taskWarning,
    blockedReason: 'Use the native snapshot schedules workspace for calendar, dataset and retention-impact review.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.dataProtection,
    'pool.snapshottask.update',
    'Edit snapshot schedule',
    'Change a periodic snapshot policy.',
    warning: 'Retention changes may remove existing recovery points.',
    blockedReason: 'Use the native snapshot schedules workspace for explicit calendar, dataset and retention-impact review.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'pool.snapshottask.delete',
    'Delete snapshot schedule',
    'Remove a periodic snapshot policy.',
    warning: 'Deleting a policy can change retention of existing snapshots.',
    blockedReason: 'Use the native snapshot schedules workspace to review affected retention before deleting a policy.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.dataProtection,
    'pool.snapshottask.run',
    'Run snapshot task',
    'Capture snapshots using an existing policy.',
    warning: 'New snapshots retain storage according to the saved policy.',
    blockedReason: 'Use the native snapshot schedules workspace to review the current policy before queuing a run.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.dataProtection,
    'replication.query',
    'Replication tasks',
    'Local and remote dataset replication policies.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.dataProtection,
    'replication.create',
    'Create replication task',
    'Define a replication source, destination and policy.',
    warning: _transferWarning,
    blockedReason:
        'A direction, retention and destination-overwrite preview is required.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.dataProtection,
    'replication.update',
    'Edit replication task',
    'Update a replication policy.',
    warning: _transferWarning,
    blockedReason:
        'A direction, retention and destination-overwrite preview is required.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'replication.delete',
    'Delete replication task',
    'Remove a saved replication policy.',
    warning: _taskDeleteWarning,
    blockedReason: 'Use the native replication workspace with task identity, destination and active-job review.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'replication.run',
    'Run replication',
    'Start an existing replication task.',
    warning: _transferWarning,
    blockedReason: 'Use the native replication workspace with exact source, destination and retention review.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'replication.restore',
    'Restore replication',
    'Prepare reverse-direction recovery.',
    warning: 'Restoring can overwrite destination datasets.',
    blockedReason: 'A restore wizard with source/destination and overwrite preview is required.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.dataProtection,
    'cloudsync.query',
    'Cloud Sync tasks',
    'Configured cloud copy, move and synchronization tasks.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.dataProtection,
    'cloudsync.create',
    'Create Cloud Sync task',
    'Configure cloud data movement.',
    warning: _transferWarning,
    blockedReason:
        'Provider-specific credential and direction validation is required.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.dataProtection,
    'cloudsync.update',
    'Edit Cloud Sync task',
    'Update cloud data movement settings.',
    warning: _transferWarning,
    blockedReason:
        'Provider-specific credential and direction validation is required.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'cloudsync.delete',
    'Delete Cloud Sync task',
    'Remove a saved cloud transfer task.',
    warning: _taskDeleteWarning,
    blockedReason: 'Use the native Cloud Sync workspace with identity and active-job checks. Task deletion can abort a running transfer.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'cloudsync.sync',
    'Run Cloud Sync',
    'Run a saved cloud transfer task.',
    warning: _transferWarning,
    blockedReason: 'Use the native Cloud Sync workspace with exact direction, credential reference, remote destination and deletion review.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.dataProtection,
    'cloudsync.abort',
    'Abort Cloud Sync',
    'Stop an in-progress cloud transfer.',
    warning: 'Files can remain partially transferred. Previously removed or overwritten data is not restored.',
    blockedReason: 'A transfer-owned cancellation and recovery workflow is required. Generic abort cannot bypass native pending-job ownership.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.dataProtection,
    'cloud_backup.query',
    'TrueCloud Backup tasks',
    'Configured backup tasks and status.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.dataProtection,
    'cloud_backup.list_snapshots',
    'Cloud recovery points',
    'Recovery snapshots for a saved backup task.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'cloud_backup.sync',
    'Run cloud backup',
    'Start a saved cloud backup policy.',
    warning: 'The saved retention policy can prune older recovery points.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'cloud_backup.delete',
    'Delete cloud backup task',
    'Remove a saved backup task.',
    warning: _taskDeleteWarning,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'cloud_backup.restore',
    'Restore cloud backup',
    'Recover files from a cloud recovery point.',
    warning: 'Recovery can overwrite files in the destination.',
    blockedReason:
        'A recovery browser and destination conflict preview are required.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.dataProtection,
    'rsynctask.query',
    'Rsync tasks',
    'Configured file synchronization jobs.',
    blockedReason: _rsyncNative,
  ),
  AdminOperationDefinition.change(
    AdminDomain.dataProtection,
    'rsynctask.create',
    'Create Rsync task',
    'Configure module or SSH file synchronization.',
    warning: _transferWarning,
    blockedReason: _rsyncNative,
  ),
  AdminOperationDefinition.change(
    AdminDomain.dataProtection,
    'rsynctask.update',
    'Edit Rsync task',
    'Update file synchronization settings.',
    warning: _transferWarning,
    blockedReason: _rsyncNative,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'rsynctask.delete',
    'Delete Rsync task',
    'Remove a saved file synchronization task.',
    warning: _taskDeleteWarning,
    blockedReason: _rsyncNative,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.dataProtection,
    'rsynctask.run',
    'Run Rsync task',
    'Start an existing synchronization job.',
    warning: _transferWarning,
    blockedReason: _rsyncNative,
  ),
  AdminOperationDefinition.read(
    AdminDomain.dataProtection,
    'vmware.query',
    'VMware snapshot integration',
    'Configured external VMware snapshot coordination.',
    blockedReason: _secretFlow,
  ),

  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'user.query',
    'Local users',
    'User identity and account inventory.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'user.create',
    'Create local user',
    'Create an account and configure access.',
    warning: 'Account settings control server and data access.',
    blockedReason: _accountFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'user.update',
    'Edit local user',
    'Change identity, groups, home and access.',
    warning: 'Incorrect account changes can remove administrative access.',
    blockedReason: _accountFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.credentials,
    'user.delete',
    'Delete local user',
    'Remove an account and selected related configuration.',
    warning: 'This can remove access and account-owned resources.',
    blockedReason: _accountFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'user.set_password',
    'Change user password',
    'Set a local account password.',
    warning: 'Existing credentials will stop working.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'group.query',
    'Local groups',
    'Group identities and memberships.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'group.create',
    'Create local group',
    'Create a group for account and data permissions.',
    warning: 'Group membership can grant access to data or administration.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'group.update',
    'Edit local group',
    'Change a group and its members.',
    warning: 'Changes can revoke or grant privileges.',
    blockedReason: _accountFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.credentials,
    'group.delete',
    'Delete local group',
    'Remove an account group.',
    warning: 'Users and file permissions may still depend on this group.',
    blockedReason: _accountFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'privilege.query',
    'Privileges',
    'Role assignments and account privileges.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'privilege.roles',
    'Available roles',
    'Roles advertised by this server.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'privilege.create',
    'Create privilege',
    'Assign roles to local or directory groups.',
    warning: 'This can grant administrative access.',
    blockedReason: _accountFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'privilege.update',
    'Edit privilege',
    'Change effective role assignments.',
    warning: 'This can grant administrator access or lock administrators out.',
    blockedReason: _accountFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.credentials,
    'privilege.delete',
    'Delete privilege',
    'Remove an effective role assignment.',
    warning: 'Administrative access may be lost.',
    blockedReason: _accountFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'directoryservices.status',
    'Directory service status',
    'Current directory integration state.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'directoryservices.config',
    'Directory service configuration',
    'Configured directory provider options.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'directoryservices.update',
    'Configure directory service',
    'Join or reconfigure an external directory.',
    warning: 'Directory changes can interrupt account and share access.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.credentials,
    'directoryservices.leave',
    'Leave directory',
    'Disconnect from the configured directory domain.',
    warning: 'Directory users may lose server and data access.',
    blockedReason: _accountFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'kerberos.realm.query',
    'Kerberos realms',
    'Configured realm and KDC definitions.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'kerberos.realm.create',
    'Create Kerberos realm',
    'Add a realm and KDC configuration.',
    warning: 'Incorrect realm settings can prevent directory authentication.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'kerberos.realm.update',
    'Edit Kerberos realm',
    'Update realm and KDC configuration.',
    warning: 'Incorrect realm settings can prevent directory authentication.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.credentials,
    'kerberos.realm.delete',
    'Delete Kerberos realm',
    'Remove a realm definition.',
    warning: 'Dependent directory authentication can stop.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'kerberos.keytab.query',
    'Kerberos keytabs',
    'Configured Kerberos key material.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'cloudsync.credentials.query',
    'Cloud credentials',
    'Configured cloud-provider credentials.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'cloudsync.credentials.create',
    'Create cloud credential',
    'Store provider access credentials.',
    warning: 'These credentials can grant access to remote data.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'cloudsync.credentials.update',
    'Rename or replace cloud credential',
    'Use the native write-only form and dependent-task safeguards.',
    warning: 'Replacing provider data replaces its whole configuration.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.credentials,
    'cloudsync.credentials.delete',
    'Delete cloud credential',
    'Inspect cloud sync and cloud backup references before deletion.',
    warning: 'Referenced credentials cannot be deleted.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'keychaincredential.query',
    'SSH credentials',
    'Stored key pairs and remote SSH connections.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'keychaincredential.create',
    'Create SSH credential',
    'Store a key pair or remote connection.',
    warning: 'Private keys and host trust require protected handling.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'keychaincredential.update',
    'Rename SSH credential',
    'Use the native unused-credential checks and protected key handling.',
    warning: 'Even name-only updates can validate keys and rebuild replication task configuration.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.credentials,
    'keychaincredential.delete',
    'Delete SSH credential',
    'Use the native fresh reference check; cascading deletion is forbidden.',
    warning: 'Stored SSH credentials are removed. Dependent tasks must first be handled separately.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'keychaincredential.generate_ssh_key_pair',
    'Generate and store SSH key pair',
    'Explicit native two-step generation and storage without disclosing private keys.',
    warning: 'Generation creates temporary key files on the server. Storage is a separate effect and cannot be automatically retried.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'certificate.query',
    'Certificates',
    'Certificate records including protected key material.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'certificate.create',
    'Create or import certificate',
    'Create certificate, CSR or ACME material.',
    warning: 'Incorrect certificates can prevent secure access.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.credentials,
    'api_key.query',
    'API keys',
    'Account API-key records.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'api_key.create',
    'Create API key',
    'Create a new authentication credential.',
    warning: 'Treat the generated key as a password.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'api_key.update',
    'Edit or rotate API key',
    'Use the native current-key safeguards and one-time secret delivery.',
    warning: 'Rotation does not terminate already authenticated sessions.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.credentials,
    'api_key.delete',
    'Delete API key',
    'Use the native account and current-key checks before deletion.',
    warning: 'Deletion does not terminate already authenticated sessions.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.credentials,
    'user.renew_2fa_secret',
    'Set up two-factor authentication',
    'Enroll an account in two-factor authentication.',
    warning: 'Incomplete enrollment can prevent sign-in.',
    blockedReason: _secretFlow,
  ),

  AdminOperationDefinition.read(
    AdminDomain.apps,
    'app.query',
    'Installed applications',
    'Application state, portals and inventory.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.apps,
    'catalog.apps',
    'Application catalog',
    'Available catalog applications and versions.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.apps,
    'app.categories',
    'Application categories',
    'Categories available on this server.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.apps,
    'catalog.get_app_details',
    'Catalog application details',
    'Details for a selected catalog application.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.apps,
    'catalog.sync',
    'Refresh application catalog',
    'Download current catalog metadata.',
    warning: 'This contacts the configured catalog and uses network bandwidth.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.apps,
    'app.create',
    'Install application',
    'Install a catalog or custom application.',
    warning: 'Applications can access storage, network and host devices.',
    blockedReason: _appSchemaFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.apps,
    'app.update',
    'Edit application',
    'Update the application values and resources.',
    warning: 'Application settings can expose data and interrupt service.',
    blockedReason: _appSchemaFlow,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.apps,
    'app.delete',
    'Delete application',
    'Uninstall an application and selected storage.',
    warning: 'Application storage may be permanently removed.',
    blockedReason:
        'A dependency and application-volume deletion preview is required.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.apps,
    'app.start',
    'Start application',
    'Start an installed application.',
    warning: 'The application will begin using configured ports and resources.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.apps,
    'app.stop',
    'Stop application',
    'Stop a running application.',
    warning: 'Users of this application will be disconnected.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.apps,
    'app.redeploy',
    'Redeploy application',
    'Recreate application workloads with saved configuration.',
    warning: 'Application service will be interrupted during redeployment.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.apps,
    'app.upgrade',
    'Upgrade application',
    'Move an application to a newer release.',
    warning: 'Application and data migrations may not be reversible.',
    blockedReason:
        'An upgrade summary, changed-values and recovery review is required.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.apps,
    'app.rollback',
    'Roll back application',
    'Return an application to an earlier version.',
    warning: 'Saved data may not be compatible with the older version.',
    blockedReason:
        'A version and application-data compatibility review is required.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.apps,
    'app.upgrade_summary',
    'Application upgrade summary',
    'Server-provided upgrade details.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.apps,
    'app.image.query',
    'Container images',
    'Cached application image inventory.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.apps,
    'app.image.delete',
    'Delete container image',
    'Remove a cached application image.',
    warning: 'Applications may need to pull this image before starting again.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.apps,
    'app.image.pull',
    'Pull container image',
    'Download an application image.',
    warning: 'This downloads third-party executable content.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.apps,
    'app.registry.query',
    'Image registries',
    'Configured registry access records.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.apps,
    'docker.config',
    'Applications storage configuration',
    'Pool and supported application service options.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.apps,
    'docker.update',
    'Configure applications storage',
    'Select or migrate the applications pool.',
    warning: 'Application availability and data location can change.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.read(
    AdminDomain.apps,
    'app.container_console_choices',
    'Application console',
    'Interactive console choices for application containers.',
    blockedReason: _terminalFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.containers,
    'container.query',
    'Containers',
    'Version-dependent system container inventory.',
    blockedReason: 'A reviewed public container adapter is not available for the 25.10 baseline; event names are not callable methods.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.containers,
    'container.device.query',
    'Container devices',
    'Version-dependent container hardware attachments.',
    blockedReason:
        'A dedicated version and device-capability adapter is required.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.virtualization,
    'vm.query',
    'Virtual machines',
    'Guest configuration and current state.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.virtualization,
    'vm.status',
    'Virtual machine status',
    'Current state of a selected guest.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.virtualization,
    'vm.start',
    'Start virtual machine',
    'Boot the selected guest.',
    warning: 'The guest will allocate configured memory, devices and network resources.',
    blockedReason: 'Use the Virtual machines workspace for UUID, power-state and resource validation.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.virtualization,
    'vm.stop',
    'Stop virtual machine',
    'Request a guest shutdown.',
    warning: _vmWarning,
    blockedReason: 'Use the Virtual machines workspace for exact identity, shutdown options and job verification.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.virtualization,
    'vm.restart',
    'Restart virtual machine',
    'Restart the selected guest.',
    warning: _vmWarning,
    blockedReason: 'Use the Virtual machines workspace for force-after-timeout review and exact job verification.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.virtualization,
    'vm.poweroff',
    'Force off virtual machine',
    'Immediately stop a guest without a clean shutdown.',
    warning: 'Unsaved guest data can be lost and filesystems can be damaged.',
    blockedReason: 'Use the Virtual machines workspace for typed target confirmation and fresh power-state validation.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.virtualization,
    'vm.create',
    'Create virtual machine',
    'Configure a new guest and its resources.',
    warning: 'Backing storage and passthrough devices require conflict checks.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.virtualization,
    'vm.update',
    'Edit virtual machine',
    'Update guest boot and resource configuration.',
    warning: 'Changes can make the guest unbootable.',
    blockedReason: 'A guest-state and device-allocation workflow is required.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.virtualization,
    'vm.delete',
    'Delete virtual machine',
    'Remove a guest and selected storage.',
    warning: 'Guest disks may be permanently destroyed.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.virtualization,
    'vm.clone',
    'Clone virtual machine',
    'Duplicate guest configuration and storage.',
    warning: 'Copied guests can conflict on network identities.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.read(
    AdminDomain.virtualization,
    'vm.device.query',
    'Virtual machine devices',
    'Attached disks, NICs, displays and passthrough hardware.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.virtualization,
    'vm.device.create',
    'Attach virtual machine device',
    'Add storage, network or passthrough hardware.',
    warning: 'Host and guest device ownership must not conflict.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.change(
    AdminDomain.virtualization,
    'vm.device.update',
    'Edit virtual machine device',
    'Change guest device settings.',
    warning: 'Changes can interrupt guest storage or networking.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.virtualization,
    'vm.device.delete',
    'Detach virtual machine device',
    'Remove a device from a guest.',
    warning: 'Removing live storage can lose guest data.',
    blockedReason: _storageWizard,
  ),
  AdminOperationDefinition.read(
    AdminDomain.virtualization,
    'vm.get_console',
    'Virtual machine serial console',
    'Open the authenticated guest console.',
    blockedReason: _terminalFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.virtualization,
    'vm.get_display_web_uri',
    'Virtual machine display',
    'Launch an authenticated guest display session.',
    blockedReason: _terminalFlow,
  ),

  AdminOperationDefinition.read(
    AdminDomain.network,
    'network.general.summary',
    'Network summary',
    'Current addresses, routes and DNS state.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.network,
    'network.configuration.config',
    'Global network configuration',
    'Hostname, gateway and resolver settings.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.network,
    'network.configuration.update',
    'Edit global networking',
    'Change server network identity or routing.',
    warning: 'Incorrect settings can disconnect this app.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.read(
    AdminDomain.network,
    'interface.query',
    'Network interfaces',
    'Physical interfaces, bridges, bonds and VLANs.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.network,
    'interface.create',
    'Create network interface',
    'Add a bridge, bond or VLAN.',
    warning: 'Network changes can disconnect this app.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.change(
    AdminDomain.network,
    'interface.update',
    'Edit network interface',
    'Change addresses and interface settings.',
    warning: 'Network changes can disconnect this app.',
    blockedReason: 'Use the dedicated physical-interface editor. Generic calls cannot own a test/check-in/rollback workflow.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.network,
    'interface.delete',
    'Delete network interface',
    'Remove a virtual network interface.',
    warning: 'Network consumers and this connection may fail.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.network,
    'interface.commit',
    'Test network changes',
    'Apply pending configuration under a rollback timer.',
    warning: 'A failed check-in must restore the prior configuration.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.change(
    AdminDomain.network,
    'interface.checkin',
    'Keep network changes',
    'Confirm tested network configuration.',
    warning: 'This prevents automatic restoration of prior settings.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.change(
    AdminDomain.network,
    'interface.rollback',
    'Revert network changes',
    'Restore previous network configuration.',
    warning: 'Current clients may be disconnected.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.read(
    AdminDomain.network,
    'staticroute.query',
    'Static routes',
    'Configured persistent route inventory.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.network,
    'staticroute.create',
    'Create static route',
    'Add a persistent destination route.',
    warning: 'Incorrect routes can disconnect management.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.change(
    AdminDomain.network,
    'staticroute.update',
    'Edit static route',
    'Update a persistent destination route.',
    warning: 'Incorrect routes can disconnect management.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.network,
    'staticroute.delete',
    'Delete static route',
    'Remove a persistent route.',
    warning: 'Hosts using this route may become unreachable.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.read(
    AdminDomain.reporting,
    'reporting.graph',
    'Graph history across instances',
    'History for one metric across its instances. Use Performance graphs for native discovery and charts.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.reporting,
    'reporting.get_data',
    'Metric history',
    'Server-provided historical observations for requested metrics.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.reporting,
    'reporting.config',
    'Reporting settings',
    'Retention and reporting service configuration.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.reporting,
    'reporting.update',
    'Configure reporting',
    'Change reporting retention and service options.',
    warning: 'Retention changes can discard historical metric data.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.reporting,
    'reporting.exporters.query',
    'Metric exporters',
    'Configured external metric destinations.',
  ),

  AdminOperationDefinition.read(
    AdminDomain.system,
    'system.general.config',
    'General settings',
    'Locale, GUI and general server configuration.',
    blockedReason: 'General configuration can contain certificate secrets. Use the native Time settings projection; other general settings need protected workflows.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'system.general.update',
    'Edit general settings',
    'Change GUI, locale and general configuration.',
    warning: 'Changing GUI addresses or certificates can prevent reconnecting.',
    blockedReason: 'Only timezone changes are supported in native Time settings. GUI addresses and certificates require a separate rollback and connectivity workflow.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'system.advanced.config',
    'Advanced settings',
    'Advanced server configuration.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'system.advanced.update',
    'Edit advanced settings',
    'Change advanced kernel, console or syslog options.',
    warning: 'Incorrect options can prevent boot or administrative access.',
    blockedReason:
        'A setting-specific validation and reboot-impact workflow is required.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'system.advanced.sed_global_password',
    'SED global password',
    'Protected disk encryption credential.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'system.ntpserver.query',
    'Time servers',
    'Configured time synchronization sources.',
    blockedReason:
        'Use the native Time settings inventory and configuration-only charts.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'system.ntpserver.create',
    'Add time server',
    'Add an NTP synchronization source.',
    warning: 'Incorrect time affects authentication, certificates and scheduled tasks.',
    blockedReason: 'Use native Time settings to review the destination probe, time-service restart and clock impact.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'system.ntpserver.update',
    'Edit time server',
    'Change an NTP synchronization source.',
    warning: 'Incorrect time affects authentication, certificates and scheduled tasks.',
    blockedReason: 'Use native Time settings to review the destination probe, time-service restart and clock impact.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.system,
    'system.ntpserver.delete',
    'Delete time server',
    'Remove a time synchronization source.',
    warning: 'Without valid sources the server clock may drift.',
    blockedReason: 'Use native Time settings to protect the last configured source and review time-service restart.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'service.query',
    'Services',
    'Server services and startup configuration.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'service.update',
    'Change service autostart',
    'Enable or disable automatic service startup.',
    warning: 'This changes which services start after the next boot.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.system,
    'service.control',
    'Control service',
    'Start, stop, restart or reload a service.',
    warning: _serviceWarning,
    blockedReason: 'Use Quick management for session-bound service control and job tracking.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'ssh.config',
    'SSH configuration',
    'Remote administration settings.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'ssh.update',
    'Configure SSH',
    'Change SSH authentication and access options.',
    warning: 'Incorrect settings can expose or disable remote access.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'mail.config',
    'Email configuration',
    'Server email delivery configuration.',
    blockedReason: 'Use native Email settings to inspect projected SMTP fields without exposing saved passwords or OAuth secrets.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'mail.update',
    'Configure email',
    'Change server notification delivery credentials.',
    warning: 'Incorrect settings can prevent important alerts.',
    blockedReason: 'Use native Email settings for write-only credentials, exact configuration review and effects on queued notifications.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'ups.config',
    'UPS configuration',
    'Power protection service settings.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'ups.update',
    'Configure UPS',
    'Change power monitoring and shutdown behavior.',
    warning: 'Incorrect UPS settings can cause an unexpected shutdown.',
    blockedReason:
        'A protected credential and power-failure policy workflow is required.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'update.config',
    'Update configuration',
    'Server update policy and preferences.',
    blockedReason: 'Use the native system-update workspace. This API can initialize server policy and is not an automatic read.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'update.available_versions',
    'Available releases',
    'Updates currently offered to this server.',
    blockedReason: 'Use the native system-update workspace and explicitly review an upstream release check.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'update.status',
    'Update status',
    'Current download and installation status.',
    blockedReason: 'Use the native system-update workspace. Checking can initialize server policy and contact the release source.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'update.download',
    'Download update',
    'Download a release to local staging storage.',
    warning: 'This uses network bandwidth and boot-pool space.',
    blockedReason: 'Use the native system-update workspace with release identity, boot-pool and job review.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.system,
    'update.run',
    'Install system update',
    'Install a selected system release.',
    warning:
        'Release changes may require a reboot and affect stored workloads.',
    blockedReason: 'A release, compatibility, boot-environment and reboot review is required.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.system,
    'update.file',
    'Upload system update',
    'Install an update supplied as a file.',
    warning: 'An invalid or incompatible update can prevent boot.',
    blockedReason: _fileFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'boot.environment.query',
    'Boot environments',
    'Available operating-system recovery environments.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'boot.environment.clone',
    'Clone boot environment',
    'Create a named OS recovery environment.',
    warning: 'This consumes boot-pool capacity.',
    blockedReason: 'Use the native boot-environment workspace with source, recovery and concurrent-job checks.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'boot.environment.keep',
    'Keep boot environment',
    'Change retention of a selected environment.',
    warning: 'Unprotected environments may be removed by cleanup policies.',
    blockedReason: 'Use the native boot-environment workspace with exact recovery-target review.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.system,
    'boot.environment.activate',
    'Activate boot environment',
    'Select the operating system for the next boot.',
    warning: 'The next reboot will start a different system environment.',
    blockedReason: 'A compatibility and next-boot review is required.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.system,
    'boot.environment.destroy',
    'Delete boot environment',
    'Remove an operating-system recovery point.',
    warning: 'The removed environment cannot be booted again.',
    blockedReason:
        'An active/next-boot and remaining-recovery-point guard is required.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'boot.scrub',
    'Scrub boot pool',
    'Check boot-pool data integrity.',
    warning: 'This increases boot-device load.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'cronjob.query',
    'Cron tasks',
    'Scheduled command inventory.',
    blockedReason: 'Use the native cron workspace. Command bodies must not enter generic inventory or logs.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'cronjob.create',
    'Create cron task',
    'Schedule a server-side command.',
    warning: 'Commands execute with the selected account authority.',
    blockedReason: 'Use the native disabled-first cron lifecycle with protected command entry and scheduler-impact review.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'cronjob.update',
    'Edit cron task',
    'Change a scheduled command.',
    warning: 'Commands can overwrite or delete server data.',
    blockedReason: 'Use the native cron lifecycle with private command preservation and explicit enablement review.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.system,
    'cronjob.delete',
    'Delete cron task',
    'Remove a scheduled command.',
    warning:
        'Removal does not cancel already-started or queued command execution.',
    blockedReason: 'Use the native disabled-task deletion review and exact-identity checks.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.system,
    'cronjob.run',
    'Run cron task',
    'Execute a configured server command.',
    warning: 'Commands can modify arbitrary server data.',
    blockedReason: 'A dedicated command execution review is required.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'tunable.query',
    'Tunables',
    'Configured kernel and system tuning values.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'tunable.create',
    'Create tunable',
    'Add a system tuning override.',
    warning: 'Incorrect values can destabilize or prevent boot.',
    blockedReason:
        'A supported-setting and reboot-impact workflow is required.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'initshutdownscript.query',
    'Startup and shutdown scripts',
    'Commands configured to run during system lifecycle.',
    blockedReason: 'Use the native projected lifecycle inventory; stored commands and script paths are protected.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'initshutdownscript.create',
    'Create lifecycle script',
    'Register a startup or shutdown command.',
    warning: 'Scripts can modify arbitrary server data.',
    blockedReason: 'Use the native disabled-first command lifecycle and separate root-execution impact review.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'audit.query',
    'Audit records',
    'Filterable security and administrative activity.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'audit.config',
    'Audit retention',
    'Audit storage and retention settings.',
    blockedReason: 'Use the native audit retention workspace for protected configuration projection.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.system,
    'audit.update',
    'Configure audit retention',
    'Change audit record retention policy.',
    warning: 'Reducing retention can remove security evidence.',
    blockedReason: 'Use the native audit retention review with evidence-loss and dataset-impact consent.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'audit.export',
    'Export audit records',
    'Download a filtered audit report.',
    blockedReason: 'Use the native audit export workspace for reviewed filters, two owned jobs and certificate-pinned bounded file delivery.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'config.save',
    'Back up system configuration',
    'Review sensitive configuration backup options and protected file export.',
    blockedReason: 'Configuration export requires the native review, pinned download and explicit protected file destination workflow.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.system,
    'config.upload',
    'Restore system configuration',
    'Review a trusted backup before configuration replacement and automatic reboot.',
    warning: 'Current settings, access and network paths can be replaced. Configuration upload automatically reboots the server.',
    blockedReason: 'Configuration restore requires the native file inspection, recovery review and same-session pinned upload workflow; generic forms cannot restore configuration.',
  ),
  AdminOperationDefinition.destructive(
    AdminDomain.system,
    'config.reset',
    'Factory reset configuration',
    'Review replacement with factory configuration and automatic reboot.',
    warning: 'Administrative, network and service configuration can be lost before any failure is reported. The native reset also requests an automatic reboot; independent recovery access is required.',
    blockedReason: 'Factory reset requires the native full-host readiness, backup and recovery review. Generic forms cannot submit reset or a no-reboot variant.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.system,
    'system.debug',
    'Create debug bundle',
    'Collect server diagnostics for support.',
    blockedReason: 'A privacy preview and secure diagnostic download workflow are required.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'support.new_ticket',
    'Create support ticket',
    'Send a support request to the vendor.',
    warning: 'This transmits server and contact information externally.',
    blockedReason: 'A recipient and privacy preview is required before external submission.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.system,
    'core.resize_shell',
    'System shell',
    'Authenticated streaming server terminal.',
    warning: 'An interactive shell can modify arbitrary server data.',
    blockedReason: _terminalFlow,
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.system,
    'system.reboot',
    'Reboot server',
    'Restart the selected TrueNAS server.',
    warning: 'All shares, applications and guests on this server can be interrupted. Verify backups and outstanding jobs.',
    blockedReason: _systemPowerNative,
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.system,
    'system.shutdown',
    'Shut down server',
    'Power off the selected TrueNAS server.',
    warning: 'All server workloads will stop. You may need physical access or out-of-band management to start it again.',
    blockedReason: _systemPowerNative,
  ),

  AdminOperationDefinition.read(
    AdminDomain.alerts,
    'alert.list',
    'Current alerts',
    'Active and dismissed server alerts.',
    blockedReason: 'Use native sanitized alert inventory; arbitrary alert payloads are not displayed.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.alerts,
    'alert.dismiss',
    'Dismiss alert',
    'Acknowledge an alert without fixing its cause.',
    warning: 'Dismissing a warning does not resolve the underlying problem.',
    blockedReason: 'Use native exact-identity review; one-shot or custom dismissal can delete alerts.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.alerts,
    'alert.restore',
    'Reopen alert',
    'Return a dismissed alert to active visibility.',
    warning: 'The alert will become visible again.',
    blockedReason: 'Use native exact-identity review and state readback.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.alerts,
    'alertclasses.config',
    'Alert policies',
    'Severity and notification policies for alert classes.',
    blockedReason: 'Use the native alert-policy workspace for validated class metadata and protected whole-map preservation.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.alerts,
    'alertclasses.update',
    'Edit alert policies',
    'Change alert severity and notification timing.',
    warning: 'The classes object replaces the entire saved override map. Omitted classes revert to defaults, including notification timing and proactive-support overrides. Suppression can hide failures; re-enabled proactive support can disclose system details externally.',
    blockedReason: 'Use native single-class review, preserved unrelated overrides, explicit support disclosure and independent readback.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.alerts,
    'alertservice.query',
    'Notification services',
    'Configured external alert destinations.',
    blockedReason: 'Use the native projected notification-services workspace. Provider credentials and arbitrary attributes are never displayed.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.alerts,
    'alertservice.create',
    'Add notification service',
    'Configure an external alert provider.',
    warning: 'Alerts can contain system details and will be sent externally.',
    blockedReason: 'Use the native notification-services or provider workspace for disabled creation, protected credentials, complete update payloads and separate transmission-impact review.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.jobs,
    'core.get_jobs',
    'Server jobs',
    'Current and recent background work.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.jobs,
    'core.job_abort',
    'Abort job',
    'Request cancellation of a selected job.',
    warning: 'A cancelled operation may leave partial work. Changes already made are not automatically undone.',
    blockedReason: 'Use the Jobs workspace for fresh job identity checks, one cancellation request and terminal-state verification.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.jobs,
    'core.job_download_logs',
    'Download job logs',
    'Download background-task output.',
    blockedReason: _fileFlow,
  ),

  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'failover.licensed',
    'HA entitlement',
    'Server-reported high-availability license state.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'failover.status',
    'HA status',
    'Reported active or standby state.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'failover.node',
    'HA node',
    'Current controller identity.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'failover.disabled.reasons',
    'HA readiness',
    'Reported reasons preventing failover.',
  ),
  AdminOperationDefinition.disruptive(
    AdminDomain.enterprise,
    'failover.become_passive',
    'Fail over controller',
    'Request the current controller become passive.',
    warning: 'This transfers service ownership and can interrupt all clients.',
    blockedReason: _haFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.enterprise,
    'failover.sync_to_peer',
    'Synchronize peer configuration',
    'Copy current configuration to the peer.',
    warning: 'Peer settings can be overwritten.',
    blockedReason: _haFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.enterprise,
    'failover.update',
    'Configure high availability',
    'Change controller failover policy.',
    warning:
        'Incorrect HA settings can interrupt service or cause split brain.',
    blockedReason: _haFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'enclosure2.query',
    'Enclosures',
    'Detected chassis and slot inventory.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'webui.enclosure.dashboard',
    'Enclosure dashboard',
    'Physical enclosure layout and per-slot disk status.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.enterprise,
    'enclosure2.set_slot_status',
    'Identify enclosure slot',
    'Change a supported slot indicator.',
    warning: 'Verify chassis and slot identity before manipulating any physical disk.',
    blockedReason: 'A hardware-mapped enclosure diagram and exact slot selection are required.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'jbof.query',
    'JBOF enclosures',
    'Configured NVMe expansion enclosures.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'fc.fc_host.query',
    'Fibre Channel hosts',
    'Detected or configured FC host adapters.',
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'fcport.query',
    'Fibre Channel mappings',
    'Configured FC port and target mappings.',
  ),
  AdminOperationDefinition.change(
    AdminDomain.enterprise,
    'fcport.create',
    'Create Fibre Channel mapping',
    'Expose a target through an FC port.',
    warning: _shareWarning,
    blockedReason: _haFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'kmip.config',
    'KMIP configuration',
    'External key-management settings.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.enterprise,
    'kmip.update',
    'Configure KMIP',
    'Change external encryption-key management.',
    warning: 'Incorrect settings can make encrypted data inaccessible.',
    blockedReason: _encryptionFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'ipmi.lan.query',
    'Out-of-band management',
    'BMC network channel configuration.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.enterprise,
    'ipmi.lan.update',
    'Configure IPMI',
    'Change BMC management connectivity.',
    warning: 'Incorrect settings can remove emergency remote access.',
    blockedReason: _networkTransaction,
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'tn_connect.config',
    'TrueNAS Connect status',
    'Cloud registration and connectivity configuration.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.change(
    AdminDomain.enterprise,
    'tn_connect.update',
    'Configure TrueNAS Connect',
    'Change cloud management registration.',
    warning: 'This changes external access and registration.',
    blockedReason: _secretFlow,
  ),
  AdminOperationDefinition.read(
    AdminDomain.enterprise,
    'truecommand.config',
    'TrueCommand status',
    'Remote management registration configuration.',
    blockedReason: _secretFlow,
  ),
];
