name: truedash
description: An unofficial planning-era TrueNAS connection client.
publish_to: none
version: 0.1.0+1
environment:
  sdk: ^3.13.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: '>=3.0.3 <4.0.0'
  flutter_secure_storage: 11.0.0
  win32: 6.4.0
  ffi: 2.2.0
  crypto: 3.0.7
  truenas_api:
    path: ../../packages/truenas_api
  truedash_design_system:
    path: ../../packages/truedash_design_system
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=5.0.0 <7.0.0'
flutter:
  uses-material-design: true
